isochron: rcv: initialize sin_zero field of struct sockaddr_in
gcc 7.3.1 for armv7 complains that struct sockaddr_in does not have a
full initializer:

isochron/rcv.c:898:2: error: missing initializer for field ‘sin_zero’ of
‘struct sockaddr_in’ [-Werror=missing-field-initializers]
  };
  ^

wtf. Add an initializer for sin_zero as well, although I was under the
impression that structure members without explicit initializers are
already set to zero.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>