isochron: log: use memcpy in buf_copy_verbatim
gcc warns:

In file included from /usr/include/string.h:495,
                 from isochron/log.c:10:
In function ‘strncpy’,
    inlined from ‘buf_copy_verbatim’ at isochron/log.c:651:2,
    inlined from ‘isochron_printf_one_packet’ at isochron/log.c:675:9:
error: ‘__builtin_strncpy’ output truncated before terminating nul copying
as many bytes from a string as its length [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
isochron/log.c: In function ‘isochron_printf_one_packet’:
isochron/log.c:675:9: note: length computed here
  675 |    rc = buf_copy_verbatim(buf_ptr, buf_end_ptr, fmt_ptr,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  676 |             strlen(fmt_ptr));
      |             ~~~~~~~~~~~~~~~~

It is actually safe in our case to use strncpy(dest, src, strlen(src)),
because we manually NULL-terminate the buffer later in
isochron_printf_one_packet() by doing "*buf_ptr = 0".

Anyway silence the warning by doing a plain memcpy.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>