isochron: fix build error due to missing type definitions
isochron.c includes isochron.h, and last commit added a new function
prototype to that header, which causes these build errors:

In file included from isochron/isochron.c:8:
isochron/isochron.h:11:6: error: unknown type name ‘bool’
   11 |      bool omit_sync, bool quiet, bool taprio, bool txtime,
      |      ^~~~
isochron/isochron.h:11:22: error: unknown type name ‘bool’
   11 |      bool omit_sync, bool quiet, bool taprio, bool txtime,
      |                      ^~~~
isochron/isochron.h:11:34: error: unknown type name ‘bool’
   11 |      bool omit_sync, bool quiet, bool taprio, bool txtime,
      |                                  ^~~~
isochron/isochron.h:11:47: error: unknown type name ‘bool’
   11 |      bool omit_sync, bool quiet, bool taprio, bool txtime,
      |                                               ^~~~
isochron/isochron.h:12:6: error: unknown type name ‘__s64’
   12 |      __s64 advance_time);
      |      ^~~~~

The fact of the matter is, isochron.h is not self-sufficient and that
should be fixed.

Fixes: afff3709d5dc ("isochron: add the ability to parse its own logs")
Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>